language: ruby
rvm:
  - 2.0.0
  - 2.1.0

env:
  - TESTENV=openldap
  - TESTENV=apacheds

# https://docs.travis-ci.com/user/hosts/
addons:
  hosts:
    - ad1.ghe.dev
    - ad2.ghe.dev

before_install:
  - echo "deb http://ftp.br.debian.org/debian stable main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update

install:
  - if [ "$TESTENV" = "openldap" ]; then ./script/install-openldap; fi
  - bundle install

script:
  - ./script/cibuild-$TESTENV

matrix:
  fast_finish: true
notifications:
  email: false
